---
- ros_topic_name: "/clock"
  gz_topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS
- ros_topic_name: "/audibot/imu"
  gz_topic_name: "/audibot/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"
  direction: GZ_TO_ROS
- ros_topic_name: "/audibot/twist"
  gz_topic_name: "/model/audibot/twist"
  ros_type_name: "geometry_msgs/msg/TwistStamped"
  gz_type_name: "gz.msgs.Twist"
  direction: GZ_TO_ROS
- ros_topic_name: "/audibot/steering_cmd"
  gz_topic_name: "/model/audibot/steering_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/audibot/brake_cmd"
  gz_topic_name: "/model/audibot/brake_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/audibot/throttle_cmd"
  gz_topic_name: "/model/audibot/throttle_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/audibot/speed_cmd"
  gz_topic_name: "/model/audibot/speed_cmd"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: ROS_TO_GZ
- ros_topic_name: "/audibot/gear_cmd"
  gz_topic_name: "/model/audibot/gear_cmd"
  ros_type_name: "std_msgs/msg/UInt32"
  gz_type_name: "gz.msgs.UInt32"
  direction: ROS_TO_GZ
- ros_topic_name: "/joint_states"
  gz_topic_name: "/model/audibot/joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS
- ros_topic_name: "/tf"
  gz_topic_name: "/model/audibot/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
- ros_topic_name: "/audibot/fix"
  gz_topic_name: "/audibot/navsat"
  ros_type_name: "sensor_msgs/msg/NavSatFix"
  gz_type_name: "gz.msgs.NavSat"
  direction: GZ_TO_ROS
- ros_topic_name: "/audibot/gnss_heading"
  gz_topic_name: "/model/audibot/gnss_heading"
  ros_type_name: "std_msgs/msg/Float64"
  gz_type_name: "gz.msgs.Double"
  direction: GZ_TO_ROS